# Generated by Django 3.2.13 on 2022-08-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbv_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AlterField(
            model_name='content',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='cbv_blog.post'),
        ),
    ]
